.TH GEDIT 1 "17 July 2022"
.SH NAME
\fBgedit\fP \- a general-purpose text editor

.SH SYNOPSIS
.br
.B gedit
[\fIOPTION\fR...] [\fIFILE\fR...] [+\fILINE\fR[:\fICOLUMN\fR]]
.br
.B gedit
[\fIOPTION\fR...] -

.SH DESCRIPTION
.B gedit
is an easy-to-use and general-purpose text editor. Its development started
in 1998, at the beginnings of the GNOME project, with a good integration with
that desktop environment.

You can use it to write simple notes and documents, or you can enable more
advanced features that are useful for software development.

.LP
.SH OPTIONS
        
.TP
\fB\-\-encoding\fR
Set the character encoding to be used for opening the files listed on the command line.
.TP
\fB\-\-list-encodings\fR
Display list of possible values for the encoding option and exit.
.TP
\fB\-\-new\-window\fR
Create a new toplevel window in an existing instance of
.B gedit.
.TP
\fB\-\-new\-document\fR
Create a new document in an existing instance of
.B gedit.
.TP
\fB\-s, \-\-standalone\fR
Run
.B gedit
in standalone mode.
.TP
\fB\-w, \-\-wait\fR
Open files and block the
.B gedit
process.
.TP
\fB\-\-help\fR
Prints the command line options.
.TP
\fB\-\-version\fR
Output version information and exit.
.TP
\fBFILE\fR
Specifies the file to open when
.B gedit
starts. If this is not specified,
.B gedit
will load a blank file with an "Unsaved Document" label. Multiple files can be loaded if they are
separated by spaces.
.B gedit
also supports handling of remote files. For example, you can pass the location
of a webpage to
.B gedit
, like "http://www.gnome.org", or load a file from a FTP server,
like "ftp://ftp.gnome.org/robots.txt".
.TP
\fB-\fR
.B gedit will read from stdin
.TP
\fB+LINE\fR
For the first file, go to the line specified by LINE (do not insert a space between the "+" sign and the number).
If LINE is missing, go to the last line.
.TP
\fBCOLUMN\fR
For the first file, go to the column specified by COLUMN.
If COLUMN is missing, go to the first column.

.SH BUGS
If you find a bug, please report it at the GNOME bug tracker. See: https://gedit-technology.github.io/apps/gedit/reporting-bugs.html
.SH AUTHORS
.\" Top 5 authors (to not have a too long list), by relative contribution
.\" (number of commits at the time of writing).
Paolo Borelli
.br
Sébastien Wilmet
.br
Ignacio Casal Quinteiro
.br
Jesse van den Kieboom
.br
Paolo Maggi
.br
and many others.
